name: DevOps Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v3

      - name: Step 2 - List files
        run: ls

      - name: Step 3 - Show current directory
        run: pwd

      - name: Step 4 - Print custom message
        run: echo "Pipeline is working step by step"