name: Multi Step Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Step
        run: echo "Building the project..."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test Step
        run: exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy Step
        run: echo "Deploying project..."